-- Fix Favorites Table Schema (Robust Version)
-- Run this in Supabase SQL Editor to fix "Not Storing" issues due to Schema Mismatch

-- 1. Drop existing table if it exists (to start fresh)
DROP TABLE IF EXISTS public.favorites;

-- 2. Create table with loose constrains (TEXT id) to support any ID type
CREATE TABLE public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- Using TEXT to be compatible with both UUIDs and other ID formats
    item_id TEXT NOT NULL,
    type TEXT NOT NULL, -- 'song', 'album', 'playlist'
    item_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Prevent duplicate favorites for the same item
    CONSTRAINT favorites_user_item_unique UNIQUE (user_id, item_id)
);

-- 3. Enable Row Level Security
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- 4. Create wide-open policies (Backend handles auth validation)
-- Allow read access
CREATE POLICY "Enable read access for all users" ON public.favorites
    FOR SELECT USING (true);

-- Allow insert access
CREATE POLICY "Enable insert access for all users" ON public.favorites
    FOR INSERT WITH CHECK (true);

-- Allow update access
CREATE POLICY "Enable update access for all users" ON public.favorites
    FOR UPDATE USING (true);

-- Allow delete access
CREATE POLICY "Enable delete access for all users" ON public.favorites
    FOR DELETE USING (true);
