-- SQL Script to create the 'favorites' table in Supabase
-- Run this in your Supabase SQL Editor

-- NOTE: Check your 'users' table ID type. 
-- If 'users.id' is a BIGINT (number), change 'user_id UUID' to 'user_id BIGINT' below.
-- If 'users.id' is a UUID (string likes), leave as is.

CREATE TABLE IF NOT EXISTS public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    item_id TEXT NOT NULL,
    type TEXT NOT NULL,
    item_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Prevent duplicate favorites for the same item
    CONSTRAINT favorites_user_item_unique UNIQUE (user_id, item_id)
);

-- Enable Row Level Security (Best Practice, though Backend handles access)
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- If you were using Supabase Auth, you would add policies here.
-- Since you are using a custom 'users' table and a Node.js backend, 
-- the backend handles authorization.
