-- Create recently_played table
create table public.recently_played (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Using text to support both UUID and Mongo IDs
  item_id text not null,
  item_data jsonb not null default '{}'::jsonb,
  played_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicate entries for same user+track
  constraint recently_played_user_item_key unique (user_id, item_id)
);

-- Index for faster retrieval by date
create index recently_played_user_date_idx on public.recently_played (user_id, played_at desc);

-- Enable RLS (Optional, depending on your setup)
alter table public.recently_played enable row level security;

-- Policy (adjust as needed if using Supabase Auth)
create policy "Users can view their own history"
  on public.recently_played for select
  using (true); -- Modify this if you want strict auth checks, e.g. auth.uid()::text = user_id

create policy "Users can insert their own history"
  on public.recently_played for insert
  with check (true);

create policy "Users can update their own history"
  on public.recently_played for update
  using (true);

create policy "Users can delete their own history"
  on public.recently_played for delete
  using (true);
